### ISSUE TITLE
UnmodifiableIterable

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#114]
Let's introduce `UnmodifiableIterable` which wraps another iterable and throws if `remove()` is called.

**Comment by Timmeey** [comment]
@yegor256 so i i had an UnmodifieableIterable i would assume that every call to iterator() would lead to the same sequence of elements. BUt how would you guarantee that behaviour?

If i take a Collection (which implements iterable) and wrap this collection in the UnmodifiableInterable, changes to the underlying Collection would still result in a change in the Iterable, after the next .iterator() call.

I can imagine `UnmodifiableIterator` since an iterator is inherently unmodifiable if it has his remove() method removed. I already had that problem with the `IterableAsList` #105 when the underlying iterable changes

**Comment by yegor256** [comment]
@Timmeey it's fixed, see 3f42592
