### ISSUE TITLE
Immutable.java:40-44: Original collection should be...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos#1236]
The puzzle `1224-6c7b441d` from #1224 has to be resolved: 

https://github.com/yegor256/cactoos/blob/b9a9beec64fece8f0a8d7734bab88185d3ea4ecf/src/main/java/org/cactoos/collection/Immutable.java#L40-L44

The puzzle was created by iakunin on 10-Nov-19. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@paulodamaso[/z](https://www.0crat.com/u/paulodamaso) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#1236](https://github.com/yegor256/cactoos/issues/1236) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#1236](https://github.com/yegor256/cactoos/issues/1236) assigned to @victornoel[/z](https://www.0crat.com/u/victornoel), here is [why](https://www.0crat.com/footprint/C63314D6Z/44cd54fd-11e9-4c15-a3a7-f280bb20d592); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by victornoel** [comment]
@paulodamaso @iakunin  I'm a bit bothered by this job (which stems fro #1224 by @quantumlexa) because it highlights something contradictory in the objectives of the collection decorators in cactoos:
- on the one hand, the decorators (as a general pattern) are there to augment existing objects in a lazy way.
- on the other hand, the collection decorators are actually not decorator, but new objects with their own state constructed from existing ones.

Both ways are correct, but we shouldn't mix them up.

Currently, `Iterable` and `Iterator` decorators act as real decorators (as defined above) because those two interfaces have a nice object oriented behaviour made for lazyness.

But collections, lists, sets, maps, etc, are not like that, they are meant to store data. Not to be "decorated". If you want to decorate a collection, you use the `Iterable` decorator and it's good enough.

So back to `Immutable`: what does it mean to have an  `Immutable` decorator?
- do we want to decorate an existing collection to be sure it's not mutable when passed to someone else ?
- or do we want to create a new collection, that is immutable by definition?
  - and btw what sense does it make to create a new collection that implements a mutable interface just to make it immutable?
   - and also: this one can be realised by cloning the collection and decoratingh it with the `Immutable` (real) decorator as discussed in the point above.

The example in the original issue (#1224) that brought us here is "stupid" when looked at through the lenses of real decorators that decorate existing proper objects: of course the wrapped collection is still mutable, and it's normal, it's a mutable collection! If I open a file in read-only from Java, it won't prevent someone from modifying the file on dik, it's the same situation.

So: what should I do here? I don't agree with cloning the collection, I think `Immutable` should stay a decorator, and be renamed `Unmodifiable` to be unambiguous and consistent with how some of the other libs working on collection do. For example Eclipse Collection (which btw is a mature object oriented collection library) have an interface `ImmutableCollection` that has NO methods for mutability AND have implementation of `Collection` that are unmodifiable and behave like our `Immutable`.

I also think we should enforce the way the classes in the `collection`, `list`, `set` and `map` packages work so that they provide various collection implementations that play well with the decorator available in `iterable` but do not act as decorator because it does not make sense:
- actually some of the classes there already follow this contract by cloning the input collection (but `Immutable` shouldn't be one of them)
- but they do follow incorrectly, for example `list.Sorted` should maintain order upon later insertion (which is not the case currently).

I'm proposing not a full change of direction, but a clarification of the current design.

@paulodamaso if we can first decide what to do with this issue, I will then create a new issue to discuss and if accepted, organise the work around my proposal.

**Comment by victornoel** [comment]
@0crat wait for ARC

**Comment by 0crat** [comment]
> @0crat wait for ARC ([here](https://github.com/yegor256/cactoos/issues/1236#issuecomment-553560479))

@victornoel The impediment for [#1236](https://github.com/yegor256/cactoos/issues/1236) was registered successfully by @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by fabriciofx** [comment]
@victornoel @paulodamaso I think the main problem is to define what is *immutability*. To @yegor256 it's just to not change attributes values (they're attributed only in the constructor/construction phase, and to achieve it, we declare attributes using `final` keyword). To functional paradigma people, immutability is a *"complete new"* object. Why *"complete new"*? Because not all objects are copied. They use a [Persistent Data Structure](https://en.wikipedia.org/wiki/Persistent_data_structure) under the table, to achieve a perfomatic solution.
So, I think we should define what kind of immutability we're talking first. WDYT?

**Comment by victornoel** [comment]
@fabriciofx I'm pretty sure we are safe to say we are not talking about functional immutability until now, hence my proposal to rename the class to `Unmodifiable`. Then if we want to go into the field of PDS, let's do, but we should not imagine we can tackle such a domain with the interfaces from a Java collections :)

**Comment by fabriciofx** [comment]
@victornoel to me, no problem to rename it `Unmodifiable`. But there is a fundamental question: one of Cactoos [principles](https://www.elegantobjects.org/#principles) is: *No mutable objects*. So, collections, lists, interable should be unmodifiable by default or not? If yes, `CollectionsOf`, `ListOf` and `IterableOf` should return unmodifiable/immutable collections by default; if not `Unmodifiable` decoration makes sense. Thus, what's the way? @paulodamaso ?

**Comment by victornoel** [comment]
@fabriciofx 
> But there is a fundamental question: one of Cactoos principles is: No mutable objects. So, collections, lists, interable should be unmodifiable by default or not? If yes, CollectionsOf, ListOf and IterableOf should return unmodifiable/immutable collections by default; if not Unmodifiable decoration makes sense

See @yegor256 opinion on that matter here: https://github.com/yegor256/cactoos/issues/898#issuecomment-540505384
> Keep in mind that 100% immutability is not only impossible, but is against the spirit of OOP

More generally, I think there is a confusion here between object mutability and mutability in the domain: when you look at Java's `File` class, it is an immutable object, but it handles mutable concepts in its domain. This is the same for collections here IMHO.

**Comment by victornoel** [comment]
@paulodamaso ping?

**Comment by paulodamaso** [comment]
@victornoel I think that we shgould go this way:
> do we want to decorate an existing collection to be sure it's not mutable when passed to someone else ?
I just have some concerns about renaming it because we already have a lot of reference around the term `Immutable`, and I don't want to break this using another term.

**Comment by victornoel** [comment]
@paulodamaso ok, thank you, then I will remove the todo and tidy things up in terms of documentation.

**Comment by victornoel** [comment]
@0crat wait for #1253 to be merged

**Comment by 0crat** [comment]
> @0crat wait for #1253 to be merged ([here](https://github.com/yegor256/cactoos/issues/1236#issuecomment-560088155))

@victornoel Job [#1236](https://github.com/yegor256/cactoos/issues/1236) is already on hold

**Comment by 0pdd** [comment]
The puzzle `1224-6c7b441d` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @victornoel[/z](https://www.0crat.com/u/victornoel), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment]
@0crat quality good

**Comment by 0crat** [comment]
Order was finished, quality is "good": +35 point(s) just awarded to @victornoel[/z](https://www.0crat.com/u/victornoel)

**Comment by 0crat** [comment]
Quality review completed: +4 point(s) just awarded to @sereshqua[/z](https://www.0crat.com/u/sereshqua)
