### ISSUE TITLE
Using Sticky classes as cache doesn't work

### ISSUE THREAD

**Issue by piotrkot** [yegor256/cactoos#1426]
I really like Cactoos approach but I'm missing a replacement for Guava Cache (https://github.com/google/guava/wiki/CachesExplained).
Sticky classes provide some of the functionalities but cache expiration or refresh must be implemented by the programmer.
Do you plan to implement it?

**Comment by andreoss** [comment]
@victornoel @piotrkot 

There is https://github.com/g4s8/cactoos-cache, which provides additional implementations of caching `Scalar`.
Though it would be nicer (and more OO) to inject cache directly to `Sticky` (as propesed here https://www.pragmaticobjects.com/chapters/012_caching_for_objects.html) 

For example:
```
public final class Sticky<T> implements Scalar<T> {
    
    private final Cache<T> cache;
    private final Scalar<T> scalar;
    
    public Sticky(final Scalar<T> scalar) {
        this(scalar, new EmptyCache<>())
    }

    @Override
    public T value() throws Exception {
        return this.cache.compute(this.scalar).value();
    }
}
```

As for #1423, the implementation (based on `Sticky`) is borrowed from `takes` (passed a review there), so no extra thoughts were given to the caching mechanics.

**Comment by skapral** [comment]
@andreoss @victornoel 

> Though it would be nicer (and more OO) to inject cache directly to Sticky (as proposed here https://www.pragmaticobjects.com/chapters/012_caching_for_objects.html)

I'd like to add 2 cents on the comment above:

1. Hiding scalar out of the constructor contract is not a good idea:

```java
// having just this is insufficient
public Sticky(final Scalar<T> scalar) {
        this(scalar, new EmptyCache<>())
}

// should be like this:
public Sticky(final Scalar<T> scalar, Cache<T> cache) {
        this(scalar, cache)
}

public Sticky(final Scalar<T> scalar) {
        this(scalar, new EmptyCache<>())
}
```

The reason is: cache is not only the place that keeps memoized chunks. Cache also defines, for how long, and for which scope the memoized value is kept. Original request was to add an ability to control it by programmer, and it is totally valid point. Cache scope and expiration should be controllable by a client.

2. The most non-trivial part following by this direction is picking up a key for a cache. Example uses scalar:

```java
return this.cache.compute(this.scalar).value();
```

...but scalar is an object. That raises crucial question: how to compare the objects. How to understand that `this.scalar` is the same as `that.scalar`. The most and the only optimal way of doing it for objects-cache-keys is [equivalence reasoning](https://www.pragmaticobjects.com/chapters/009_equivalence_101.html) --- for similar calls on two equivalent objects (two equivalent scalars in this case), memoized value should be reused. Otherwise, there will inevitably be cache misses, which will neglect all value in caches.

For equivalence logic generation, there is [oo-equivalence](https://github.com/pragmatic-objects/oo-equivalence). Also, I have a primitive cache artifacts in [oo-memoized](https://github.com/pragmatic-objects/oo-memoized). Feel free to ask me questions or report issues to these repos.

**Comment by victornoel** [comment]
@andreoss @skapral thank you for your feedbacks. I wasn't aware of cactoos-cache, but I believe this should be where all this discussion should happen then.

I will thus close this issue and consider caching out of scope of cactoos and redirect people to https://github.com/g4s8/cactoos-cache

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#1426` is not assigned, can't get performer
