### ISSUE TITLE
Add Capitalized EE version of StringUtils.capitalize

### ISSUE THREAD

**Issue by kokodyn** [yegor256/cactoos#1466]
Hi all
I would like to add  EO version of StringUtils.capitalize
[StringUtils.capitalize](http://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/StringUtils.html#capitalize-java.lang.String-)
But it's seems first I need to add class "Titled" to handle title case converting.
Is it ok for you?

I hope for your understanding, this is my first pull request to open source project.

**Comment by victornoel** [comment]
@kokodyn I'm not exactly sure what you mean :)

I see there is #1465 which introduce `Capitalized`: is this PR outdated? It seems to implement `Capitalized` as you want it, no? Or do you mean that to simplify the PR, you would need `Titled`?

**Comment by victornoel** [comment]
@kokodyn can you explain?

**Comment by victornoel** [comment]
@kokodyn from what I understand, I believe we can handle all of that from the PR you made, see my comment https://github.com/yegor256/cactoos/pull/1465#discussion_r495467732. No need for a new ticket :)

**Comment by kokodyn** [comment]
@victornoel 
To simplify logic I created new PR to introduce Titled.

**Comment by victornoel** [comment]
@kokodyn I'm going to close this then. Please next time try to take things in the right order either by creating first a ticket for a new requirement not supported by cactoos or if you contribute a PR, by going iteratively and incrementally with `@todo`s.

We are in no rush to get PRs and solutions, we must first examine the problems as they come :)

By the way @kokodyn, woudln't you be interested in joining zerocracy and the cactoos project in order to contribute to it as part of the team? It would be great to have more DEV :)
See http://www.zerocracy.com/faq.html
