### ISSUE TITLE
add Xor class to allow exclusive disjunction

### ISSUE THREAD

**Issue by kokodyn** [yegor256/cactoos#1510]
Hi
I would like to propose to add new class which allow logical operation Xor.
I created PR with draft version #1509

**Comment by victornoel** [comment]
@kokodyn please either create a ticket and wait for it to be put in scope and managed with 0crat (with the delay it incurs and the fact it will be assigned to someone else) xor (see what I did? ;) create a PR (with the risk of having it refused), but not both :)
Thanks, it would ease my life :)

I will close this since we already have the PR then!
