### ISSUE TITLE
Printing and parsing of dates and times

### ISSUE THREAD

**Issue by yegor256** [yegor256/cactoos#444]
To be honest, I'm sick of date parsing and printing in Java 8 Date and Time API. How about we create our own object-oriented one at `org.cactoos.time`? Here is how it should work, I believe.

Printing:

```java
String text = new DateAsText(new Date(), "%Y-%m-%d").asString();
String text = new DateAsText(System.currentTimeMillis(), "%Y-%m-%d").asString();
String text = new DateAsText(ZonedDateTime.now()).asString(); // ISO 8601 is the default one
```

Parsing:

```java
Date date = new DateOf("2017-10-17", "%Y-%m-%d").value();
Date date = new DateOf("October 16, 2017", DateTimeFormatter.ISO_LOCAL_DATE).value();
```

With time zones:

```java
String text = new DateAsText(new Date(), "%Y-%m-%d", "PST").asString();
Date date = new DateOf("2017-01-01", "%Y-%m-%d", ZoneOffset.UTC).value();
```

That's it.

Later, we can create, for example:

```java
Date date = new Shifted(date, 5, "month").value();
```

**Comment by Timmeey** [comment]
`Date date = new Shifted(date, 5, "month").value();`

Please don't use "String" (month) as identifier for the unit. Noone can ever get the naming right. Was ist capitalized? Does ms exists as a uni? or was it even ms not MilliSecond?

Also i'm always struggling with date formatting since i can NEVER remember what character means what. Was MM minute or Month, or was it the month number or month name?

Maybe we could do something with enums here? At least the SHIFTING unit can definitely be done with an enum. Not so sure about the formatting yet.

**Comment by yegor256** [comment]
@Timmeey we can use java.time.temporal.ChronoUnit enum: https://docs.oracle.com/javase/8/docs/api/java/time/temporal/ChronoUnit.html

**Comment by svendiedrichsen** [comment]
@yegor256 How about using the Java8 time classes LocalDate or ZonedDate instead of Date?

**Comment by svendiedrichsen** [comment]
@yegor256 I would like to contribute on this.

**Comment by yegor256** [comment]
@svendiedrichsen please, go ahead, but slowly. Don't make big pull requests, since they may get stuck in reviews.

**Comment by svendiedrichsen** [comment]
@yegor256 Sorry for this. But I didn't think of 2 classes and 2 tests being such a big PR.

**Comment by svendiedrichsen** [comment]
@yegor256 Can this be closed now?

**Comment by yegor256** [comment]
@svendiedrichsen yes, many thanks!
