### ISSUE TITLE
PRs: commit linting

### ISSUE THREAD

**Issue by llorllale** [yegor256/cactoos#988]
There have been several commits with messages that don't meet our quality standards. I will attempt to enforce some rules using [gitlint](https://github.com/jorisroovers/gitlint).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#988](https://github.com/yegor256/cactoos/issues/988), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by 0crat** [comment]
Job `gh:yegor256/cactoos#988` already assigned to @llorllale, can't assign to @llorllale

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by llorllale** [comment]
@llorllale fixed in #989

**Comment by 0crat** [comment]
Job [#988](https://github.com/yegor256/cactoos/issues/988) is not in the agenda of @llorllale[/z](https://www.0crat.com/u/llorllale), can't retrieve data and time of add
